%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'DSA_Exogenous_Debt_fast_scaling_up';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('DSA_Exogenous_Debt_fast_scaling_up.log');
M_.exo_names = 'iz_shock';
M_.exo_names_tex = 'iz\_shock';
M_.exo_names_long = 'iz_shock';
M_.exo_names = char(M_.exo_names, 'iz_shocka');
M_.exo_names_tex = char(M_.exo_names_tex, 'iz\_shocka');
M_.exo_names_long = char(M_.exo_names_long, 'iz_shocka');
M_.exo_names = char(M_.exo_names, 'borrowd');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowd');
M_.exo_names_long = char(M_.exo_names_long, 'borrowd');
M_.exo_names = char(M_.exo_names, 'borrowdneg');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowdneg');
M_.exo_names_long = char(M_.exo_names_long, 'borrowdneg');
M_.exo_names = char(M_.exo_names, 'borrowdnega');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowdnega');
M_.exo_names_long = char(M_.exo_names_long, 'borrowdnega');
M_.exo_names = char(M_.exo_names, 'borrowdc');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowdc');
M_.exo_names_long = char(M_.exo_names_long, 'borrowdc');
M_.exo_names = char(M_.exo_names, 'borrowdcneg');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowdcneg');
M_.exo_names_long = char(M_.exo_names_long, 'borrowdcneg');
M_.exo_names = char(M_.exo_names, 'borrowda');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowda');
M_.exo_names_long = char(M_.exo_names_long, 'borrowda');
M_.exo_names = char(M_.exo_names, 'borrowdca');
M_.exo_names_tex = char(M_.exo_names_tex, 'borrowdca');
M_.exo_names_long = char(M_.exo_names_long, 'borrowdca');
M_.exo_names = char(M_.exo_names, 'grants_shock');
M_.exo_names_tex = char(M_.exo_names_tex, 'grants\_shock');
M_.exo_names_long = char(M_.exo_names_long, 'grants_shock');
M_.exo_names = char(M_.exo_names, 'remit');
M_.exo_names_tex = char(M_.exo_names_tex, 'remit');
M_.exo_names_long = char(M_.exo_names_long, 'remit');
M_.exo_names = char(M_.exo_names, 'f_shock1');
M_.exo_names_tex = char(M_.exo_names_tex, 'f\_shock1');
M_.exo_names_long = char(M_.exo_names_long, 'f_shock1');
M_.exo_names = char(M_.exo_names, 'f_shock2');
M_.exo_names_tex = char(M_.exo_names_tex, 'f\_shock2');
M_.exo_names_long = char(M_.exo_names_long, 'f_shock2');
M_.exo_names = char(M_.exo_names, 'px');
M_.exo_names_tex = char(M_.exo_names_tex, 'px');
M_.exo_names_long = char(M_.exo_names_long, 'px');
M_.exo_names = char(M_.exo_names, 'pm');
M_.exo_names_tex = char(M_.exo_names_tex, 'pm');
M_.exo_names_long = char(M_.exo_names_long, 'pm');
M_.exo_names = char(M_.exo_names, 'pmm');
M_.exo_names_tex = char(M_.exo_names_tex, 'pmm');
M_.exo_names_long = char(M_.exo_names_long, 'pmm');
M_.endo_names = 'qx';
M_.endo_names_tex = 'qx';
M_.endo_names_long = 'qx';
M_.endo_names = char(M_.endo_names, 'qn');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn');
M_.endo_names_long = char(M_.endo_names_long, 'qn');
M_.endo_names = char(M_.endo_names, 'kx');
M_.endo_names_tex = char(M_.endo_names_tex, 'kx');
M_.endo_names_long = char(M_.endo_names_long, 'kx');
M_.endo_names = char(M_.endo_names, 'kn');
M_.endo_names_tex = char(M_.endo_names_tex, 'kn');
M_.endo_names_long = char(M_.endo_names_long, 'kn');
M_.endo_names = char(M_.endo_names, 'lx');
M_.endo_names_tex = char(M_.endo_names_tex, 'lx');
M_.endo_names_long = char(M_.endo_names_long, 'lx');
M_.endo_names = char(M_.endo_names, 'L_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_n');
M_.endo_names_long = char(M_.endo_names_long, 'L_n');
M_.endo_names = char(M_.endo_names, 'ix');
M_.endo_names_tex = char(M_.endo_names_tex, 'ix');
M_.endo_names_long = char(M_.endo_names_long, 'ix');
M_.endo_names = char(M_.endo_names, 'in');
M_.endo_names_tex = char(M_.endo_names_tex, 'in');
M_.endo_names_long = char(M_.endo_names_long, 'in');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'rx');
M_.endo_names_tex = char(M_.endo_names_tex, 'rx');
M_.endo_names_long = char(M_.endo_names_long, 'rx');
M_.endo_names = char(M_.endo_names, 'rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'rn');
M_.endo_names_long = char(M_.endo_names_long, 'rn');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'pz');
M_.endo_names_tex = char(M_.endo_names_tex, 'pz');
M_.endo_names_long = char(M_.endo_names_long, 'pz');
M_.endo_names = char(M_.endo_names, 'pn');
M_.endo_names_tex = char(M_.endo_names_tex, 'pn');
M_.endo_names_long = char(M_.endo_names_long, 'pn');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'bstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'bstar');
M_.endo_names_long = char(M_.endo_names_long, 'bstar');
M_.endo_names = char(M_.endo_names, 'Rz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rz');
M_.endo_names_long = char(M_.endo_names_long, 'Rz');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'eh');
M_.endo_names_tex = char(M_.endo_names_tex, 'eh');
M_.endo_names_long = char(M_.endo_names_long, 'eh');
M_.endo_names = char(M_.endo_names, 'T');
M_.endo_names_tex = char(M_.endo_names_tex, 'T');
M_.endo_names_long = char(M_.endo_names_long, 'T');
M_.endo_names = char(M_.endo_names, 'ze');
M_.endo_names_tex = char(M_.endo_names_tex, 'ze');
M_.endo_names_long = char(M_.endo_names_long, 'ze');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names_long = char(M_.endo_names_long, 'dc');
M_.endo_names = char(M_.endo_names, 'iz');
M_.endo_names_tex = char(M_.endo_names_tex, 'iz');
M_.endo_names_long = char(M_.endo_names_long, 'iz');
M_.endo_names = char(M_.endo_names, 'dplot');
M_.endo_names_tex = char(M_.endo_names_tex, 'dplot');
M_.endo_names_long = char(M_.endo_names_long, 'dplot');
M_.endo_names = char(M_.endo_names, 'ynom');
M_.endo_names_tex = char(M_.endo_names_tex, 'ynom');
M_.endo_names_long = char(M_.endo_names_long, 'ynom');
M_.endo_names = char(M_.endo_names, 'netbwconc');
M_.endo_names_tex = char(M_.endo_names_tex, 'netbwconc');
M_.endo_names_long = char(M_.endo_names_long, 'netbwconc');
M_.endo_names = char(M_.endo_names, 'rext');
M_.endo_names_tex = char(M_.endo_names_tex, 'rext');
M_.endo_names_long = char(M_.endo_names_long, 'rext');
M_.endo_names = char(M_.endo_names, 'grants');
M_.endo_names_tex = char(M_.endo_names_tex, 'grants');
M_.endo_names_long = char(M_.endo_names_long, 'grants');
M_.endo_names = char(M_.endo_names, 'rextg');
M_.endo_names_tex = char(M_.endo_names_tex, 'rextg');
M_.endo_names_long = char(M_.endo_names_long, 'rextg');
M_.endo_names = char(M_.endo_names, 'tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'tot');
M_.endo_names_long = char(M_.endo_names_long, 'tot');
M_.endo_names = char(M_.endo_names, 'totmm');
M_.endo_names_tex = char(M_.endo_names_tex, 'totmm');
M_.endo_names_long = char(M_.endo_names_long, 'totmm');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'miu2');
M_.endo_names_tex = char(M_.endo_names_tex, 'miu2');
M_.endo_names_long = char(M_.endo_names_long, 'miu2');
M_.endo_names = char(M_.endo_names, 'growth');
M_.endo_names_tex = char(M_.endo_names_tex, 'growth');
M_.endo_names_long = char(M_.endo_names_long, 'growth');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'beta_t');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_t');
M_.param_names_long = char(M_.param_names_long, 'beta_t');
M_.param_names = char(M_.param_names, 'delta_x');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_x');
M_.param_names_long = char(M_.param_names_long, 'delta_x');
M_.param_names = char(M_.param_names, 'delta_n');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_n');
M_.param_names_long = char(M_.param_names_long, 'delta_n');
M_.param_names = char(M_.param_names, 'delta_z');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_z');
M_.param_names_long = char(M_.param_names_long, 'delta_z');
M_.param_names = char(M_.param_names, 'alpha_k');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_k');
M_.param_names_long = char(M_.param_names_long, 'alpha_k');
M_.param_names = char(M_.param_names, 'alpha_z');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_z');
M_.param_names_long = char(M_.param_names_long, 'alpha_z');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'psi_x');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_x');
M_.param_names_long = char(M_.param_names_long, 'psi_x');
M_.param_names = char(M_.param_names, 'psi_n');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_n');
M_.param_names_long = char(M_.param_names_long, 'psi_n');
M_.param_names = char(M_.param_names, 'xi_n');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_n');
M_.param_names_long = char(M_.param_names_long, 'xi_n');
M_.param_names = char(M_.param_names, 'xi_x');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_x');
M_.param_names_long = char(M_.param_names_long, 'xi_x');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'alpha_x');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_x');
M_.param_names_long = char(M_.param_names_long, 'alpha_x');
M_.param_names = char(M_.param_names, 'alpha_n');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_n');
M_.param_names_long = char(M_.param_names_long, 'alpha_n');
M_.param_names = char(M_.param_names, 'g');
M_.param_names_tex = char(M_.param_names_tex, 'g');
M_.param_names_long = char(M_.param_names_long, 'g');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'gama_n');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_n');
M_.param_names_long = char(M_.param_names_long, 'gama_n');
M_.param_names = char(M_.param_names, 'gama_x');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_x');
M_.param_names_long = char(M_.param_names_long, 'gama_x');
M_.param_names = char(M_.param_names, 'gama_m');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_m');
M_.param_names_long = char(M_.param_names_long, 'gama_m');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'rho_x');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_x');
M_.param_names_long = char(M_.param_names_long, 'rho_x');
M_.param_names = char(M_.param_names, 'rho_m');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_m');
M_.param_names_long = char(M_.param_names_long, 'rho_m');
M_.param_names = char(M_.param_names, 'R_zo');
M_.param_names_tex = char(M_.param_names_tex, 'R\_zo');
M_.param_names_long = char(M_.param_names_long, 'R_zo');
M_.param_names = char(M_.param_names, 'yo');
M_.param_names_tex = char(M_.param_names_tex, 'yo');
M_.param_names_long = char(M_.param_names_long, 'yo');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'ho');
M_.param_names_tex = char(M_.param_names_tex, 'ho');
M_.param_names_long = char(M_.param_names_long, 'ho');
M_.param_names = char(M_.param_names, 'r_do');
M_.param_names_tex = char(M_.param_names_tex, 'r\_do');
M_.param_names_long = char(M_.param_names_long, 'r_do');
M_.param_names = char(M_.param_names, 'rstar');
M_.param_names_tex = char(M_.param_names_tex, 'rstar');
M_.param_names_long = char(M_.param_names_long, 'rstar');
M_.param_names = char(M_.param_names, 'share_bstar');
M_.param_names_tex = char(M_.param_names_tex, 'share\_bstar');
M_.param_names_long = char(M_.param_names_long, 'share_bstar');
M_.param_names = char(M_.param_names, 'share_b');
M_.param_names_tex = char(M_.param_names_tex, 'share\_b');
M_.param_names_long = char(M_.param_names_long, 'share_b');
M_.param_names = char(M_.param_names, 'share_d');
M_.param_names_tex = char(M_.param_names_tex, 'share\_d');
M_.param_names_long = char(M_.param_names_long, 'share_d');
M_.param_names = char(M_.param_names, 'fo');
M_.param_names_tex = char(M_.param_names_tex, 'fo');
M_.param_names_long = char(M_.param_names_long, 'fo');
M_.param_names = char(M_.param_names, 'miu');
M_.param_names_tex = char(M_.param_names_tex, 'miu');
M_.param_names_long = char(M_.param_names_long, 'miu');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'a_k');
M_.param_names_tex = char(M_.param_names_tex, 'a\_k');
M_.param_names_long = char(M_.param_names_long, 'a_k');
M_.param_names = char(M_.param_names, 'a_z');
M_.param_names_tex = char(M_.param_names_tex, 'a\_z');
M_.param_names_long = char(M_.param_names_long, 'a_z');
M_.param_names = char(M_.param_names, 'nu_x');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_x');
M_.param_names_long = char(M_.param_names_long, 'nu_x');
M_.param_names = char(M_.param_names, 'nu_n');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_n');
M_.param_names_long = char(M_.param_names_long, 'nu_n');
M_.param_names = char(M_.param_names, 'VA_n');
M_.param_names_tex = char(M_.param_names_tex, 'VA\_n');
M_.param_names_long = char(M_.param_names_long, 'VA_n');
M_.param_names = char(M_.param_names, 'ro');
M_.param_names_tex = char(M_.param_names_tex, 'ro');
M_.param_names_long = char(M_.param_names_long, 'ro');
M_.param_names = char(M_.param_names, 'To');
M_.param_names_tex = char(M_.param_names_tex, 'To');
M_.param_names_long = char(M_.param_names_long, 'To');
M_.param_names = char(M_.param_names, 'd_o');
M_.param_names_tex = char(M_.param_names_tex, 'd\_o');
M_.param_names_long = char(M_.param_names_long, 'd_o');
M_.param_names = char(M_.param_names, 'bo');
M_.param_names_tex = char(M_.param_names_tex, 'bo');
M_.param_names_long = char(M_.param_names_long, 'bo');
M_.param_names = char(M_.param_names, 'zo');
M_.param_names_tex = char(M_.param_names_tex, 'zo');
M_.param_names_long = char(M_.param_names_long, 'zo');
M_.param_names = char(M_.param_names, 'P_zo');
M_.param_names_tex = char(M_.param_names_tex, 'P\_zo');
M_.param_names_long = char(M_.param_names_long, 'P_zo');
M_.param_names = char(M_.param_names, 'Lo');
M_.param_names_tex = char(M_.param_names_tex, 'Lo');
M_.param_names_long = char(M_.param_names_long, 'Lo');
M_.param_names = char(M_.param_names, 'a_n');
M_.param_names_tex = char(M_.param_names_tex, 'a\_n');
M_.param_names_long = char(M_.param_names_long, 'a_n');
M_.param_names = char(M_.param_names, 'a_x');
M_.param_names_tex = char(M_.param_names_tex, 'a\_x');
M_.param_names_long = char(M_.param_names_long, 'a_x');
M_.param_names = char(M_.param_names, 'm');
M_.param_names_tex = char(M_.param_names_tex, 'm');
M_.param_names_long = char(M_.param_names_long, 'm');
M_.param_names = char(M_.param_names, 'r_dco');
M_.param_names_tex = char(M_.param_names_tex, 'r\_dco');
M_.param_names_long = char(M_.param_names_long, 'r_dco');
M_.param_names = char(M_.param_names, 'dco');
M_.param_names_tex = char(M_.param_names_tex, 'dco');
M_.param_names_long = char(M_.param_names_long, 'dco');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'lambda1');
M_.param_names_tex = char(M_.param_names_tex, 'lambda1');
M_.param_names_long = char(M_.param_names_long, 'lambda1');
M_.param_names = char(M_.param_names, 'lambda2');
M_.param_names_tex = char(M_.param_names_tex, 'lambda2');
M_.param_names_long = char(M_.param_names_long, 'lambda2');
M_.param_names = char(M_.param_names, 'lambda3');
M_.param_names_tex = char(M_.param_names_tex, 'lambda3');
M_.param_names_long = char(M_.param_names_long, 'lambda3');
M_.param_names = char(M_.param_names, 'lambda4');
M_.param_names_tex = char(M_.param_names_tex, 'lambda4');
M_.param_names_long = char(M_.param_names_long, 'lambda4');
M_.param_names = char(M_.param_names, 'eo');
M_.param_names_tex = char(M_.param_names_tex, 'eo');
M_.param_names_long = char(M_.param_names_long, 'eo');
M_.param_names = char(M_.param_names, 'eho');
M_.param_names_tex = char(M_.param_names_tex, 'eho');
M_.param_names_long = char(M_.param_names_long, 'eho');
M_.param_names = char(M_.param_names, 's_s');
M_.param_names_tex = char(M_.param_names_tex, 's\_s');
M_.param_names_long = char(M_.param_names_long, 's_s');
M_.param_names = char(M_.param_names, 'grantso');
M_.param_names_tex = char(M_.param_names_tex, 'grantso');
M_.param_names_long = char(M_.param_names_long, 'grantso');
M_.param_names = char(M_.param_names, 'remito');
M_.param_names_tex = char(M_.param_names_tex, 'remito');
M_.param_names_long = char(M_.param_names_long, 'remito');
M_.param_names = char(M_.param_names, 'a_ratio');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ratio');
M_.param_names_long = char(M_.param_names_long, 'a_ratio');
M_.param_names = char(M_.param_names, 'zeo');
M_.param_names_tex = char(M_.param_names_tex, 'zeo');
M_.param_names_long = char(M_.param_names_long, 'zeo');
M_.param_names = char(M_.param_names, 'sigma_x');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_x');
M_.param_names_long = char(M_.param_names_long, 'sigma_x');
M_.param_names = char(M_.param_names, 'sigma_n');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_n');
M_.param_names_long = char(M_.param_names_long, 'sigma_n');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'q_xo');
M_.param_names_tex = char(M_.param_names_tex, 'q\_xo');
M_.param_names_long = char(M_.param_names_long, 'q_xo');
M_.param_names = char(M_.param_names, 'q_no');
M_.param_names_tex = char(M_.param_names_tex, 'q\_no');
M_.param_names_long = char(M_.param_names_long, 'q_no');
M_.param_names = char(M_.param_names, 'bstaro');
M_.param_names_tex = char(M_.param_names_tex, 'bstaro');
M_.param_names_long = char(M_.param_names_long, 'bstaro');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'nug');
M_.param_names_tex = char(M_.param_names_tex, 'nug');
M_.param_names_long = char(M_.param_names_long, 'nug');
M_.exo_det_nbr = 0;
M_.exo_nbr = 16;
M_.endo_nbr = 39;
M_.param_nbr = 72;
M_.orig_endo_nbr = 39;
M_.aux_vars = [];
M_.Sigma_e = zeros(16, 16);
M_.Correlation_matrix = eye(16, 16);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('DSA_Exogenous_Debt_fast_scaling_up_static');
erase_compiled_function('DSA_Exogenous_Debt_fast_scaling_up_dynamic');
M_.lead_lag_incidence = [
 1 15 0;
 2 16 0;
 3 17 0;
 4 18 0;
 0 19 0;
 0 20 0;
 0 21 54;
 0 22 55;
 0 23 0;
 0 24 56;
 0 25 57;
 0 26 58;
 0 27 0;
 0 28 0;
 0 29 59;
 0 30 60;
 5 31 0;
 6 32 0;
 0 33 0;
 7 34 0;
 8 35 0;
 9 36 0;
 0 37 61;
 0 38 0;
 0 39 0;
 10 40 0;
 11 41 0;
 0 42 0;
 12 43 0;
 0 44 0;
 0 45 0;
 13 46 0;
 0 47 0;
 14 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;]';
M_.nstatic = 17;
M_.nfwrd   = 8;
M_.npred   = 14;
M_.nboth   = 0;
M_.nsfwrd   = 8;
M_.nspred   = 14;
M_.ndynamic   = 22;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:16];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(39, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(16, 1);
M_.params = NaN(72, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 215;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
load dsa_params.mat;          
for i=1:length(M_.params)
deep_parameter_name = M_.param_names(i,:);
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])
end   
load steady_state_values.mat;
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 25 ) = T_ini;
oo_.steady_state( 1 ) = q_x_ini;
oo_.steady_state( 2 ) = q_n_ini;
oo_.steady_state( 3 ) = k_x_ini;
oo_.steady_state( 4 ) = k_n_ini;
oo_.steady_state( 5 ) = L_x_ini;
oo_.steady_state( 6 ) = L_n_ini;
oo_.steady_state( 17 ) = z_ini;
oo_.steady_state( 26 ) = ze_ini;
oo_.steady_state( 12 ) = P_k_ini;
oo_.steady_state( 13 ) = P_z_ini;
oo_.steady_state( 23 ) = e_ini;
oo_.steady_state( 24 ) = eh_ini;
oo_.steady_state( 9 ) = w_ini;
oo_.steady_state( 14 ) = P_n_ini;
oo_.steady_state( 15 ) = P_ini;
oo_.steady_state( 7 ) = i_x_ini;
oo_.steady_state( 8 ) = i_n_ini;
oo_.steady_state( 16 ) = h_ini;
oo_.steady_state( 10 ) = r_x_ini;
oo_.steady_state( 11 ) = r_n_ini;
oo_.steady_state( 28 ) = i_z_ini;
oo_.steady_state( 22 ) = r_ini;
oo_.steady_state( 18 ) = bstar_ini;
oo_.steady_state( 19 ) = R_z_ini;
oo_.steady_state( 20 ) = M_.params(44);
oo_.steady_state( 21 ) = M_.params(43);
oo_.steady_state( 27 ) = M_.params(52);
oo_.steady_state( 29 ) = M_.params(43);
oo_.exo_steady_state( 11 ) = M_.params(62);
oo_.steady_state( 33 ) = M_.params(61);
oo_.steady_state( 30 ) = M_.params(25);
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 34 ) = M_.params(29)+M_.params(72);
oo_.steady_state( 32 ) = oo_.steady_state(34)+M_.params(67);
oo_.exo_steady_state( 14 ) = 1;
oo_.exo_steady_state( 15 ) = 1;
oo_.exo_steady_state( 16 ) = 1;
oo_.steady_state( 37 ) = P_n_ini/oo_.exo_steady_state(14);
oo_.steady_state( 35 ) = oo_.exo_steady_state(14)/oo_.exo_steady_state(15);
oo_.steady_state( 36 ) = oo_.exo_steady_state(14)/oo_.exo_steady_state(16);
oo_.steady_state( 38 ) = M_.params(34);
oo_.steady_state( 39 ) = M_.params(16);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
steady;
resid(1)
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
set_shocks(0,9:1000, 1, 1.5);
set_shocks(0,1, 2, 2.5);
set_shocks(0,2, 2, 3.5);
set_shocks(0,3, 2, 3.5);
set_shocks(0,4, 2, 3.3);
set_shocks(0,5, 2, 2.9);
set_shocks(0,6, 2, 2.5);
set_shocks(0,7, 2, 2.2);
set_shocks(0,8, 2, 2);
set_shocks(0,1, 3, 4);
set_shocks(0,2, 3, 5);
set_shocks(0,3, 3, 4);
set_shocks(0,4, 3, 3);
set_shocks(0,5, 3, 2);
set_shocks(0,6, 3, 1);
set_shocks(0,7, 3, 0.75);
set_shocks(0,8, 3, 0.5);
set_shocks(0,1, 4, 0);
set_shocks(0,2, 4, 0);
set_shocks(0,3, 4, 0);
set_shocks(0,4, 4, 0);
set_shocks(0,5, 4, 0);
set_shocks(0,6, 4, 0);
set_shocks(0,7, 4, 0);
set_shocks(0,8, 4, 0);
set_shocks(0,9, 4, 1.0125);
set_shocks(0,10, 4, 1.0125);
set_shocks(0,11, 4, 1.0125);
set_shocks(0,12, 4, 1.0125);
set_shocks(0,13, 4, 1.0125);
set_shocks(0,14, 4, 1.0125);
set_shocks(0,15, 4, 1.0125);
set_shocks(0,16, 4, 1.0125);
set_shocks(0,17, 4, 1.0125);
set_shocks(0,18, 4, 1.0125);
set_shocks(0,19, 4, 1.0125);
set_shocks(0,20, 4, 1.0125);
set_shocks(0,21, 4, 1.0125);
set_shocks(0,22, 4, 1.0125);
set_shocks(0,23, 4, 1.0125);
set_shocks(0,24, 4, 1.0125);
set_shocks(0,25, 4, 1.0125);
set_shocks(0,26, 4, 1.0125);
set_shocks(0,27, 4, 1.0125);
set_shocks(0,28, 4, 0);
set_shocks(0,29, 4, 0);
set_shocks(0,30, 4, 0);
set_shocks(0,1, 10, 0.4);
set_shocks(0,2, 10, 0.4);
set_shocks(0,3, 10, 0.4);
set_shocks(0,4, 10, 0.4);
set_shocks(0,5, 10, 0.4);
set_shocks(0,6, 10, 0.4);
set_shocks(0,7, 10, 0.4);
set_shocks(0,8, 10, 0.4);
set_shocks(0,9, 10, 0.2);
set_shocks(0,10, 10, 0.2);
set_shocks(0,11, 10, 0.2);
set_shocks(0,12, 10, 0.2);
set_shocks(0,13, 10, 0.2);
set_shocks(0,14, 10, 0.2);
set_shocks(0,15, 10, 0.2);
set_shocks(0,16, 10, 0.2);
set_shocks(0,17, 10, 0.2);
set_shocks(0,18, 10, 0.2);
set_shocks(0,19, 10, 0.2);
set_shocks(0,20, 10, 0.2);
set_shocks(0,21, 10, 0.2);
set_shocks(0,22, 10, 0.2);
set_shocks(0,23, 10, 0.2);
set_shocks(0,24, 10, 0.2);
set_shocks(0,25, 10, 0.2);
set_shocks(0,26, 10, 0.2);
set_shocks(0,27, 10, 0.2);
set_shocks(0,28, 10, 0.2);
set_shocks(0,29, 10, 0.2);
set_shocks(0,30, 10, 0.2);
set_shocks(0,1:1000, 11, 4);
set_shocks(0,1:1000, 14, 1);
set_shocks(0,1:1000, 15, 1);
M_.exo_det_length = 0;
M_.sigma_e_is_diagonal = 1;
options_.periods = 1000;
simul();
save('DSA_Exogenous_Debt_fast_scaling_up_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('DSA_Exogenous_Debt_fast_scaling_up_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('DSA_Exogenous_Debt_fast_scaling_up_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('DSA_Exogenous_Debt_fast_scaling_up_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('DSA_Exogenous_Debt_fast_scaling_up_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
